/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/clrKfT1Tdri
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import { Button } from "@/components/ui/button";
import { JSX, SVGProps, useState } from "react";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";

import { Label } from "@/components/ui/label";

import { QueryResult, QueryResultRow, sql } from "@vercel/postgres";

import { useRouter } from "next/navigation";

import { useSearchParams } from "next/navigation";
import Error from "next/error";

/*import { makeIPInspector } from 'next-fortress/ip'

export const middleware = makeIPInspector('125.103.20.82', {
  type: 'redirect',
  destination: '/this-page-probably-does-not-exist'
})*/

export type Tile = {
  id: string;
  name: string;
  description: string;
};

export function Validation(props: {
  receivedVGI: any;
  receivedOPTS: any;
  receivedCATS: any;
  receivedVOTS: any;
  receivedVOTX: any;
  receivedEXQS: any;
  receivedEXOP: any;
  currentIP: string;
}) {
  //   class IndivExtraQuestion {
  //     ID: string;
  //     name: string;
  //     maxVotes: number;
  //     orderNo: number;

  //     constructor(ID: string, name: string, maxVotes: number, orderNo: number) {
  //       this.ID = ID;
  //       this.name = name;
  //       this.maxVotes = maxVotes;
  //       this.orderNo = orderNo;
  //     }
  //   }

  //   class IndivExtraOption {
  //     ID: string;
  //     QID: string;
  //     name: string;
  //     orderNo: number;

  //     constructor(ID: string, QID: string, name: string, orderNo: number) {
  //       this.ID = ID;
  //       this.QID = QID;
  //       this.name = name;
  //       this.orderNo = orderNo;
  //     }
  //   }

  //   class IndivOption {
  //     ID: string;
  //     catID: string;
  //     name: string;
  //     description: string;
  //     orderNo: number;

  //     constructor(
  //       ID: string,
  //       catID: string,
  //       name: string,
  //       description: string,
  //       orderNo: number
  //     ) {
  //       this.ID = ID;
  //       this.catID = catID;
  //       this.name = name;
  //       this.description = description;
  //       this.orderNo = orderNo;
  //     }
  //   }

  //   class IndivCat {
  //     ID: string;
  //     name: string;
  //     maxvotes: number;
  //     orderNo: number;

  //     constructor(ID: string, name: string, maxvotes: number, orderNo: number) {
  //       this.ID = ID;
  //       this.name = name;
  //       this.maxvotes = maxvotes;
  //       this.orderNo = orderNo;
  //     }
  //   }

  //   class IndivVote {
  //     ID: string;
  //     votetime: string;
  //     voteoption: string;
  //     entrycount: number;
  //     IP: string;

  //     constructor(
  //       ID: string,
  //       votetime: string,
  //       voteoption: string,
  //       entrycount: number,
  //       IP: string
  //     ) {
  //       this.ID = ID;
  //       this.votetime = votetime;
  //       this.voteoption = voteoption;
  //       this.entrycount = entrycount;
  //       this.IP = IP;
  //     }
  //   }

  //   class IndivVoteX {
  //     ID: string;
  //     votetime: string;
  //     qid: string;
  //     qans: string;
  //     entrycount: number;
  //     IP: string;

  //     constructor(
  //       ID: string,
  //       votetime: string,
  //       qid: string,
  //       qans: string,
  //       entrycount: number,
  //       IP: string
  //     ) {
  //       this.ID = ID;
  //       this.votetime = votetime;
  //       this.qid = qid;
  //       this.qans = qans;
  //       this.entrycount = entrycount;
  //       this.IP = IP;
  //     }
  //   }

  //   const router = useRouter();
  //   const jumpVoting = () => {
  //     var queries = "";
  //     router.replace("/validation?" + queries);
  //   };

  //   const [votingSet, setVotingSet] = useState<boolean>(
  //     props.receivedVGI[0].votingset
  //   );
  //   const [votingDateS, setVotingDateS] = useState<string>(
  //     props.receivedVGI[0].votingstart
  //   );
  //   const [votingDateE, setVotingDateE] = useState<string>(
  //     props.receivedVGI[0].votingend
  //   );
  //   const [votingName, setVotingName] = useState<string>(
  //     props.receivedVGI[0].name
  //   );
  //   const [votingDescription, setVotingDescription] = useState<string>(
  //     props.receivedVGI[0].description
  //   );

  //   const transformPlainObjectToOptions = (obj: QueryResultRow[]) => {
  //     var listToReturn: IndivOption[] = [];
  //     obj.forEach((element) => {
  //       listToReturn.push(
  //         new IndivOption(
  //           element.id,
  //           element.categoryid,
  //           element.name,
  //           element.description,
  //           element.orderno
  //         )
  //       );
  //     });
  //     return listToReturn;
  //   };

  //   const transformPlainObjectToCategories = (obj: QueryResultRow[]) => {
  //     var listToReturn: IndivCat[] = [];
  //     obj.forEach((element) => {
  //       listToReturn.push(
  //         new IndivCat(
  //           element.id,
  //           element.name,
  //           element.maxvotes,
  //           element.orderno
  //         )
  //       );
  //     });
  //     return listToReturn;
  //   };

  //   const transformPlainObjectToVotes = (obj: QueryResultRow[]) => {
  //     var listToReturn: IndivVote[] = [];
  //     obj.forEach((element) => {
  //       listToReturn.push(
  //         new IndivVote(
  //           element.id,
  //           element.votetime,
  //           element.voteoption,
  //           element.entrycount,
  //           element.ip
  //         )
  //       );
  //     });
  //     return listToReturn;
  //   };

  //   const transformPlainObjectToVoteX = (obj: QueryResultRow[]) => {
  //     var listToReturn: IndivVoteX[] = [];
  //     obj.forEach((element) => {
  //       listToReturn.push(
  //         new IndivVoteX(
  //           element.id,
  //           element.votetime,
  //           element.qid,
  //           element.qanswer,
  //           element.entrycount,
  //           element.ip
  //         )
  //       );
  //     });
  //     return listToReturn;
  //   };

  //   const transformPlainObjectToExtraQuestions = (obj: QueryResultRow[]) => {
  //     var listToReturn: IndivExtraQuestion[] = [];
  //     obj.forEach((element) => {
  //       listToReturn.push(
  //         new IndivExtraQuestion(
  //           element.id,
  //           element.name,
  //           element.maxvotes,
  //           element.orderno
  //         )
  //       );
  //     });
  //     return listToReturn;
  //   };

  //   const transformPlainObjectToExtraOptions = (obj: QueryResultRow[]) => {
  //     var listToReturn: IndivExtraOption[] = [];
  //     obj.forEach((element) => {
  //       listToReturn.push(
  //         new IndivExtraOption(
  //           element.id,
  //           element.qid,
  //           element.name,
  //           //element.maxvotes,
  //           element.orderno
  //         )
  //       );
  //     });
  //     return listToReturn;
  //   };

  //   const [options, setOptions] = useState<IndivOption[]>(
  //     transformPlainObjectToOptions(props.receivedOPTS)
  //   );
  //   const [categories, setCategories] = useState<IndivCat[]>(
  //     transformPlainObjectToCategories(props.receivedCATS)
  //   );

  //   const [extraQuestions, setExtraQuestions] = useState<IndivExtraQuestion[]>(
  //     transformPlainObjectToExtraQuestions(props.receivedEXQS)
  //   );

  //   const [extraOptions, setExtraOptions] = useState<IndivExtraOption[]>(
  //     transformPlainObjectToExtraOptions(props.receivedEXOP)
  //   );

  //   const [votes, setVotes] = useState<IndivVote[]>(
  //     transformPlainObjectToVotes(props.receivedVOTS)
  //   );

  //   const [voteX, setVoteX] = useState<IndivVoteX[]>(
  //     transformPlainObjectToVoteX(props.receivedVOTX)
  //   );

  //   const sParams = useSearchParams();
  //   const opts = sParams.getAll("opt");
  //   const votopts = sParams.getAll("votopt");
  //   const fp = sParams.get("fp");

  //   const optionnames = options.reduce((objAcc: any, option) => {
  //     objAcc.push(option.ID);
  //     return objAcc;
  //   }, []);

  //   try {
  //     /*

  //     ALL THE TESTS HERE MIGHT BE USELESS AF
  //     BECAUSE THEY WERE JUST PASTED HERE UPON THE DUPLICATION OF VOTING-CORE (TO MAKE THIS PAGE)
  //     AND ALL THE ADDITIONAL TESTS MUST BE DONE IN THE SERVER-SIDE CODE

  // */
  //     var optMatchTest = opts.toString() == optionnames.toString(); // options matching test (only fails if option existence or order has changed)

  //     // var inCatVoteCountTest = categories.reduce((objAcc: boolean, category) => {
  //     //   // Make this area TRY / CATCH later
  //     //   var inCategoryVotedCount = 0;
  //     //   options
  //     //     .filter((eachOption) => eachOption.catID == category.ID)
  //     //     .forEach((option) => {
  //     //       if (votopts.includes(option.ID)) {
  //     //         inCategoryVotedCount++;
  //     //       }
  //     //     });
  //     //   objAcc =
  //     //     objAcc &&
  //     //     inCategoryVotedCount <= category.maxvotes &&
  //     //     inCategoryVotedCount >= 0; // vote count test (in category >=0 && <= maxvotes)
  //     //   return objAcc;
  //     // }, true);

  //     // var inCatVoteCountTest = extraQuestions.reduce(
  //     //   (objAcc: boolean, category) => {
  //     //     // Make this area TRY / CATCH later
  //     //     var inCategoryVotedCount = 0;
  //     //     options
  //     //       .filter((eachOption) => eachOption.catID == category.ID)
  //     //       .forEach((option) => {
  //     //         if (votopts.includes(option.ID)) {
  //     //           inCategoryVotedCount++;
  //     //         }
  //     //       });
  //     //     objAcc =
  //     //       objAcc &&
  //     //       inCategoryVotedCount <= category.maxVotes &&
  //     //       inCategoryVotedCount >= 0; // vote count test (in category >=0 && <= maxvotes)
  //     //     return objAcc;
  //     //   },
  //     //   true
  //     // );

  //     var totalVoteCountTest =
  //       categories.reduce((objAcc: number, category) => {
  //         // we dont really need to use categories.reduce but its easier this way because I ctrl+v'd
  //         options
  //           .filter((eachOption) => eachOption.catID == category.ID)
  //           .forEach((option) => {
  //             if (votopts.includes(option.ID)) {
  //               // vote count test (in category >0)
  //               objAcc++;
  //             }
  //           });
  //         return objAcc;
  //       }, 0) != 0;

  //     var voteDupliTest = !votes.find(
  //       (eachVote) => eachVote.IP == props.currentIP
  //     ); // IP hit test

  //     if (!optMatchTest) {
  //       throw "optMatchTest";
  //     }
  //     // if (!inCatVoteCountTest) {
  //     //   throw "inCatVoteCountTest"; // WE'LL LATER NEED THIS KIND OF TEST FOR THE SURVEY
  //     // }
  //     if (!totalVoteCountTest) {
  //       throw "totalVoteCountTest";
  //     }
  //     if (!voteDupliTest) {
  //       throw "voteDupliTest";
  //     }
  //   } catch (e) {
  //     if (e instanceof Error) {
  //       console.log("regular error" + e);
  //     } else {
  //       console.log(e);
  //     }
  //   }

  return <></>;
}
