/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/clrKfT1Tdri
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import { Button } from "@/components/ui/button";
import {
  JSX,
  SVGProps,
  useState,
  useMemo,
  useEffect,
  CSSProperties,
} from "react";

import { useToast } from "@/components/ui/use-toast";
import { Toaster } from "@/components/ui/toaster";

import { Label } from "@/components/ui/label";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";

import { QueryResult, QueryResultRow, sql } from "@vercel/postgres";

import { useRouter } from "next/navigation";

import { Checkbox } from "@/components/ui/checkbox";

import Image from "next/image";
import { Check } from "lucide-react";

import { ClientJS } from "clientjs";
// import getBrowserFingerprint from "get-browser-fingerprint";
import { getEnabledCategories } from "trace_events";

import { detectIncognito } from "detectincognitojs";

import ReactMarkdown from "react-markdown";

import MarkdownRenderer from "./markdown-renderer";
import styles from "../styles/MarkdownContainer.module.css";

import { animFont } from "@/app/fonts";
import { Loader2 } from "lucide-react";

import { useVisitorData } from "@fingerprintjs/fingerprintjs-pro-react";
import { Skeleton } from "../ui/skeleton";

/*import { makeIPInspector } from 'next-fortress/ip'

export const middleware = makeIPInspector('125.103.20.82', {
  type: 'redirect',
  destination: '/this-page-probably-does-not-exist'
})*/

// export type Tile = {
//   id: string;
//   name: string;
//   description: string;
// };

export default function VotingCore(props: {
  receivedVGI: any;
  receivedOPTS: any;
  receivedCATS: any;
  // receivedVOTX: any;
  receivedEXQS: any;
  receivedEXOP: any;
  //receivedVOTS: any;
  //list: Tile[];
  // checkCalledByChild: any;
  //submitCalledByChild: any;
  // checkAns: any;
}) {
  class IndivExtraQuestion {
    ID: string;
    name: string;
    maxVotes: number;
    orderNo: number;

    constructor(ID: string, name: string, maxVotes: number, orderNo: number) {
      this.ID = ID;
      this.name = name;
      this.maxVotes = maxVotes;
      this.orderNo = orderNo;
    }
  }

  class IndivExtraOption {
    ID: string;
    QID: string;
    name: string;
    orderNo: number;

    constructor(ID: string, QID: string, name: string, orderNo: number) {
      this.ID = ID;
      this.QID = QID;
      this.name = name;
      this.orderNo = orderNo;
    }
  }

  class IndivOption {
    ID: string;
    catID: string;
    name: string;
    description: string;
    orderNo: number;

    constructor(
      ID: string,
      catID: string,
      name: string,
      description: string,
      orderNo: number
    ) {
      this.ID = ID;
      this.catID = catID;
      this.name = name;
      this.description = description;
      this.orderNo = orderNo;
    }
  }

  class IndivCat {
    ID: string;
    name: string;
    //maxvotes: number;
    orderNo: number;

    constructor(
      ID: string,
      name: string,
      /*maxvotes: number,*/ orderNo: number
    ) {
      this.ID = ID;
      this.name = name;
      //this.maxvotes = maxvotes;
      this.orderNo = orderNo;
    }
  }

  async function digestMessage(message: string) {
    const encoder = new TextEncoder();
    const data = encoder.encode(message);
    const hash = await crypto.subtle.digest("SHA-256", data);
    return hash;
  }

  // var rtcFPbase = "";
  // rtcFPbase.toString();
  // rtcFPbase += DetectRTC.hasWebcam.toString();
  // rtcFPbase += DetectRTC.hasMicrophone.toString(); // (has webcam device!)
  // rtcFPbase += DetectRTC.hasSpeakers.toString(); // (has microphone device!)
  // rtcFPbase += DetectRTC.isScreenCapturingSupported.toString(); // (has speakers!)
  // rtcFPbase += DetectRTC.isSctpDataChannelsSupported.toString(); // Chrome, Firefox, Opera, Edge and Android
  // rtcFPbase += DetectRTC.isRtpDataChannelsSupported.toString();
  // rtcFPbase += DetectRTC.isAudioContextSupported.toString();
  // rtcFPbase += DetectRTC.isWebRTCSupported.toString();
  // rtcFPbase += DetectRTC.isDesktopCapturingSupported.toString();
  // rtcFPbase += DetectRTC.isMobileDevice.toString();
  // rtcFPbase += DetectRTC.isWebSocketsSupported.toString();
  // rtcFPbase += DetectRTC.isWebSocketsBlocked.toString();
  // rtcFPbase +=
  //   // DetectRTC.checkWebSocketsSupport(callback).toString(); rtcFPbase +=

  //   DetectRTC.isWebsiteHasWebcamPermissions.toString();
  // rtcFPbase += DetectRTC.isWebsiteHasMicrophonePermissions.toString(); // getUserMedia allowed for HTTPs domain in Chrome?
  // rtcFPbase += DetectRTC.audioInputDevices.toString(); // getUserMedia allowed for HTTPs domain in Chrome?
  // rtcFPbase += DetectRTC.audioOutputDevices.toString(); // microphones
  // rtcFPbase += DetectRTC.videoInputDevices.toString(); // speakers
  // rtcFPbase += DetectRTC.osName.toString(); // cameras
  // rtcFPbase += DetectRTC.osVersion.toString();
  // rtcFPbase +=
  //   DetectRTC.browser.name.toString();
  // rtcFPbase += DetectRTC.browser.version.toString();
  // rtcFPbase += DetectRTC.browser.isChrome.toString();
  // rtcFPbase += DetectRTC.browser.isFirefox.toString();
  // rtcFPbase += DetectRTC.browser.isOpera.toString();
  // rtcFPbase += DetectRTC.browser.isIE.toString();
  // rtcFPbase += DetectRTC.browser.isSafari.toString();
  // rtcFPbase += DetectRTC.browser.isEdge.toString();
  // rtcFPbase +=
  //   // DetectRTC.browser.isPrivateBrowsing .toString(); rtcFPbase +=  // incognito or private modes
  //   DetectRTC.isCanvasSupportsStreamCapturing.toString();
  // rtcFPbase += DetectRTC.isVideoSupportsStreamCapturing.toString();
  // console.log(JSON.stringify(DetectRTC));

  // console.log(
  //   (
  //     DetectRTC.hasWebcam + // (has webcam device!)
  //       DetectRTC.hasMicrophone + // (has microphone device!)
  //       DetectRTC.hasSpeakers + // (has speakers!)
  //       DetectRTC.isScreenCapturingSupported + // Chrome, Firefox, Opera, Edge and Android
  //       DetectRTC.isSctpDataChannelsSupported +
  //       DetectRTC.isRtpDataChannelsSupported +
  //       DetectRTC.isAudioContextSupported +
  //       DetectRTC.isWebRTCSupported +
  //       DetectRTC.isDesktopCapturingSupported +
  //       DetectRTC.isMobileDevice +
  //       DetectRTC.isWebSocketsSupported +
  //       DetectRTC.isWebSocketsBlocked +
  //       // DetectRTC.checkWebSocketsSupport(callback)+

  //       DetectRTC.isWebsiteHasWebcamPermissions + // getUserMedia allowed for HTTPs domain in Chrome?
  //       DetectRTC.isWebsiteHasMicrophonePermissions + // getUserMedia allowed for HTTPs domain in Chrome?
  //       DetectRTC.audioInputDevices + // microphones
  //       DetectRTC.audioOutputDevices + // speakers
  //       DetectRTC.videoInputDevices + // cameras
  //       DetectRTC.osName +
  //       DetectRTC.osVersion +
  //       DetectRTC.browser.name ===
  //       "Edge" ||
  //     "Chrome" ||
  //     "Firefox" +
  //       DetectRTC.browser.version +
  //       DetectRTC.browser.isChrome +
  //       DetectRTC.browser.isFirefox +
  //       DetectRTC.browser.isOpera +
  //       DetectRTC.browser.isIE +
  //       DetectRTC.browser.isSafari +
  //       DetectRTC.browser.isEdge +
  //       // DetectRTC.browser.isPrivateBrowsing + // incognito or private modes
  //       DetectRTC.isCanvasSupportsStreamCapturing +
  //       DetectRTC.isVideoSupportsStreamCapturing
  //   ).toString()
  // );

  // const fingerprint = getBrowserFingerprint();
  // console.log(fingerprint);

  // const handleFetch = async () => {
  //   const response = await fetch("/api/generatefp", {
  //     method: "POST",
  //     headers: {
  //       "Content-Type": "application/json",
  //     },
  //     body: JSON.stringify({ client.ge }),
  //   });
  //   const result = await response.json();
  //   console.log(result.data);
  // };

  // handleFetch();
  // const fingerprint = client.getFingerprint();
  // console.log(fingerprint, client.isCookie());

  var hold5000Timeout: any, dead10000Timeout: any;

  const { toast } = useToast();

  const [checkboxes, setCheckboxes] = useState({});

  const [extraCheckboxes, setExtraCheckboxes] = useState({});

  const handleCheckboxChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { name, checked } = event.target;
    setCheckboxes((prevState) => ({
      ...(prevState as { [key: string]: boolean }),
      [name]: checked,
    }));
  };

  const handleExtraCheckboxChange = (
    event: React.ChangeEvent<HTMLInputElement>
  ) => {
    const { name, checked } = event.target;
    setExtraCheckboxes((prevState) => ({
      ...(prevState as { [key: string]: boolean }),
      [name]: checked,
    }));
  };

  const router = useRouter();
  const jumpVoting = async (inCjsfp: string) => {
    var optsArray: string[] = [],
      votoptsArray: string[] = [],
      extraoptsArray: string[] = [],
      votextraoptsArray: string[] = [];

    // for (const checkbox in checkboxesKeys) {
    //   console.log(checkbox + "HOLY MOLY THERE IS A CHECKBOX");
    // }
    var optParams = "";
    for (const property in checkboxes) {
      optParams += "opt" + "=" + property + "&";
      optsArray.push(property);
    }
    var votoptParams = "";
    checkboxesKeys
      .reduce((objAcc: any, key: string) => {
        if (checkboxes[key as keyof typeof checkboxes]) {
          objAcc.push(key);
        }
        return objAcc;
      }, [])
      .forEach((property: string) => {
        console.log(property);
        votoptParams += "votopt" + "=" + property + "&";
        votoptsArray.push(property);
      });

    var extraOptParams = "";
    for (const property in extraCheckboxes) {
      extraOptParams += "extraopt" + "=" + property + "&";
      extraoptsArray.push(property);
    }
    var votExtraOptParams = "";
    extraCheckboxesKeys
      .reduce((objAcc: any, key: string) => {
        if (extraCheckboxes[key as keyof typeof extraCheckboxes]) {
          objAcc.push(key);
        }
        return objAcc;
      }, [])
      .forEach((property: string) => {
        console.log(property);
        votExtraOptParams += "votextraopt" + "=" + property + "&";
        votextraoptsArray.push(property);
      });

    try {
      const response = await fetch("/api/validate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          opts: optsArray,
          votopts: votoptsArray,
          extraopts: extraoptsArray,
          votextraopts: votextraoptsArray,
          fp: inCjsfp || "cjsfp missing",
        }),
      });

      const data = await response.json();

      if (response.ok) {
        router.replace("/thanks");
      } else {
        if (response.status == 400) {
          router.replace("/error-vote?e=" + data.error);
        } else if (response.status == 500) {
          clearTimeout(hold5000Timeout);
          clearTimeout(dead10000Timeout);
          setIsLoadingStatus(false);
          toast({
            title: "[CE-V500] エラーが発生しました",
            description:
              "不具合のおそれがあります。再読み込みしてください。エラー情報：" +
              data.message,
            variant: "destructive",
          });
        } else if (response.status == 504) {
          clearTimeout(hold5000Timeout);
          clearTimeout(dead10000Timeout);

          setIsLoadingStatus(false);
          toast({
            title: "[CE-V504] 投票できませんでした",
            description: "不具合のおそれがあります。再読み込みしてください。",
            variant: "destructive",
          });
        } else {
          clearTimeout(hold5000Timeout);
          clearTimeout(dead10000Timeout);

          setIsLoadingStatus(false);
          toast({
            title: "[CE-VXX] 投票できませんでした",
            description: "不具合のおそれがあります。再読み込みしてください。",
            variant: "destructive",
          });
        }
      }
    } catch (err: any) {
      if (err.name == "TypeError") {
        clearTimeout(hold5000Timeout);
        clearTimeout(dead10000Timeout);

        setIsLoadingStatus(false);
        toast({
          title: "投票できませんでした",
          description:
            "インターネット接続を確認するか、再読み込みしてください。",
          variant: "destructive",
        });
      }
    }

    // router.replace(
    //   "/validation?" +
    //     optParams +
    //     votoptParams +
    //     extraOptParams +
    //     votExtraOptParams +
    //     "fp=" +
    //     cjsfp
    // );
  };

  // const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
  const handleSubmit = () => {
    // event.preventDefault();

    var checkedItemCount = 0;
    for (const [key, value] of Object.entries(checkboxes)) {
      if (value) checkedItemCount++;
    }

    var checkedExtraItemCount = 0;
    for (const [key, value] of Object.entries(extraCheckboxes)) {
      if (value) checkedExtraItemCount++;
    }

    var maxVotesTest = checkedItemCount <= maxVotes;
    var zeroVotesTest = checkedItemCount > 0;

    var maxExtraVotesTest = extraQuestions.reduce(
      (objAcc: boolean, key: IndivExtraQuestion) => {
        return (
          objAcc &&
          extraCheckboxesKeys.filter(
            (eachExtraCheckboxKey) =>
              extraOptions.find(
                (eachExtraOption) => eachExtraOption.ID == eachExtraCheckboxKey
              )?.QID == key.ID &&
              extraCheckboxes[
                eachExtraCheckboxKey as keyof typeof extraCheckboxes
              ]
          ).length <= (key?.maxVotes ?? 99999)
        );
      },
      true
    );

    console.log(maxVotesTest + ", " + zeroVotesTest + ", " + maxExtraVotesTest);

    if (!maxVotesTest) {
      toast({
        title: maxVotes + "票が上限です！",
        description: "不具合のおそれがあります。再読み込みしてください。",
        variant: "destructive",
      });

      setIsDialogOpen(false);
    } else if (!zeroVotesTest) {
      toast({
        title: "白票は入れられません！",
        description: "1候補以上選択してください。",
        variant: "destructive",
      });

      setIsDialogOpen(false);
    } else if (!maxExtraVotesTest) {
      toast({
        title: "アンケートの票数が過多です！",
        description: "不具合のおそれがあります。再読み込みしてください。",
        variant: "destructive",
      });

      setIsDialogOpen(false);
    } else {
      setIsLoadingStatus(true);
      hold5000Timeout = setTimeout(() => {
        toast({
          title: "少々お待ちください…",
          description: "投票を試みています。",
          variant: "default",
        });
      }, 5000);
      dead10000Timeout = setTimeout(() => {
        clearTimeout(dead10000Timeout);
        setIsLoadingStatus(false);
        toast({
          title: "投票できませんでした",
          description:
            "インターネット接続を確認するか、再読み込みしてください。",
          variant: "destructive",
        });
      }, 10000);

      jumpVoting(cjsfp);
      console.log(
        checkboxesKeys.reduce((objAcc: any, key: string) => {
          if (checkboxes[key as keyof typeof checkboxes]) {
            objAcc.push(key);
          }
          return objAcc;
        }, [])
      );
    }
  };

  const [votingSet, setVotingSet] = useState<boolean>(
    props.receivedVGI[0].votingset
  );
  const [votingDateS, setVotingDateS] = useState<string>(
    props.receivedVGI[0].votingstart
  );
  const [votingDateE, setVotingDateE] = useState<string>(
    props.receivedVGI[0].votingend
  );
  const [maxVotes, setMaxVotes] = useState<number>(
    props.receivedVGI[0].maxvotes
  );
  const [votingName, setVotingName] = useState<string>(
    props.receivedVGI[0].name
  );
  const [votingDescription, setVotingDescription] = useState<string>(
    props.receivedVGI[0].description
  );
  const dayStartTime = props.receivedVGI[0].daystarttime;
  const dayEndTime = props.receivedVGI[0].dayendtime;

  const transformPlainObjectToOptions = (obj: QueryResultRow[]) => {
    var listToReturn: IndivOption[] = [];
    obj.forEach((element) => {
      listToReturn.push(
        new IndivOption(
          element.id,
          element.categoryid,
          element.name,
          element.description,
          element.orderno
        )
      );
    });
    return listToReturn;
  };

  const transformPlainObjectToCategories = (obj: QueryResultRow[]) => {
    var listToReturn: IndivCat[] = [];
    obj.forEach((element) => {
      listToReturn.push(
        new IndivCat(
          element.id,
          element.name,
          //element.maxvotes,
          element.orderno
        )
      );
    });
    return listToReturn;
  };

  const transformPlainObjectToExtraQuestions = (obj: QueryResultRow[]) => {
    var listToReturn: IndivExtraQuestion[] = [];
    obj.forEach((element) => {
      listToReturn.push(
        new IndivExtraQuestion(
          element.id,
          element.name,
          element.maxvotes,
          element.orderno
        )
      );
    });
    return listToReturn;
  };

  const transformPlainObjectToExtraOptions = (obj: QueryResultRow[]) => {
    var listToReturn: IndivExtraOption[] = [];
    obj.forEach((element) => {
      listToReturn.push(
        new IndivExtraOption(
          element.id,
          element.qid,
          element.name,
          //element.maxvotes,
          element.orderno
        )
      );
    });
    return listToReturn;
  };

  const [options, setOptions] = useState<IndivOption[]>(
    transformPlainObjectToOptions(props.receivedOPTS)
  );
  const [categories, setCategories] = useState<IndivCat[]>(
    transformPlainObjectToCategories(props.receivedCATS)
  );

  const [extraQuestions, setExtraQuestions] = useState<IndivExtraQuestion[]>(
    transformPlainObjectToExtraQuestions(props.receivedEXQS)
  );

  const [extraOptions, setExtraOptions] = useState<IndivExtraOption[]>(
    transformPlainObjectToExtraOptions(props.receivedEXOP)
  );

  // Initialize the checkboxes state based on the checkboxData
  useState(() => {
    const initialCheckboxes: { [key: string]: boolean } = {};
    options.forEach((option) => {
      initialCheckboxes[option.ID] = false;
    });
    setCheckboxes(initialCheckboxes);
  });

  useState(() => {
    const initialExtraCheckboxes: { [key: string]: boolean } = {};
    extraOptions.forEach((extraOption) => {
      initialExtraCheckboxes[extraOption.ID] = false;
    });
    setExtraCheckboxes(initialExtraCheckboxes);
  });

  const checkboxesKeys = Object.keys(checkboxes);
  const extraCheckboxesKeys = Object.keys(extraCheckboxes);

  // let isPriv: boolean | undefined = undefined;
  const client = new ClientJS();
  // const cjsfp = client.getFingerprint();
  // console.log(cjsfp);

  const { isLoading, error, data, getData } = useVisitorData(
    { extendedResult: true },
    { immediate: true }
  );
  const cjsfp = data?.visitorId || "fp not created as data.visitorId missing";

  console.log(error ? error.message : JSON.stringify(data, null, 2));

  const compareDimensions = (dim: string) =>
    dim.includes("x") ? +dim.split("x")[0] > +dim.split("x")[1] : undefined;

  useEffect(() => {
    if (
      new Date() < new Date(votingDateS) ||
      new Date() >= new Date(votingDateE) ||
      new Date(new Date().setFullYear(1970, 0, 1)) < new Date(dayStartTime) ||
      new Date(new Date().setFullYear(1970, 0, 1)) >= new Date(dayEndTime)
    ) {
      router.replace("/error-vote?e=op");
    } else {
      detectIncognito().then(async (result) => {
        if (result.isPrivate) {
          router.replace("/error-incognito");
        } else {
          const checkIPinDatabase = async () => {
            if (!cjsfp) {
              return false;
            }
            try {
              const response = await fetch("/api/checkifvoted", {
                method: "POST",
                headers: {
                  "Content-Type": "application/json",
                },
                body: JSON.stringify({ cjsfp }),
              });

              if (!response.ok) {
                throw new Error(`Server error: ${response.status}`);
              }

              const data = await response.json();
              console.warn(cjsfp);
              console.warn(data.found);
              return data.found;
            } catch (err: any) {
              console.error("Error fetching from API:", err);
            }
          };

          if (await checkIPinDatabase()) {
            router.replace("/error-vote?e=ed");
          } else {
            if (!client.isMobile()) {
              router.replace("/error-vote?e=mb");
            } else if (compareDimensions(client.getAvailableResolution())) {
              console.log(client.getAvailableResolution());
              console.log(compareDimensions(client.getAvailableResolution()));
              router.replace("/error-vote?e=pr");
            }
          }
        }
      });
    }
  }, [data]);

  const [isPolicyChecked, setIsPolicyChecked] = useState<any>(false);
  const [isEligibilityChecked, setIsEligibilityChecked] = useState<any>(false);
  const [isSecondEligibilityChecked, setIsSecondEligibilityChecked] =
    useState<any>(false);
  const [isDialogOpen, setIsDialogOpen] = useState(false);

  const [isLoadingStatus, setIsLoadingStatus] = useState(false);

  const hashCode = (s: string) =>
    s
      .split("")
      .reduce(
        (a: number, b: string) => ((a << 5) - a + b.charCodeAt(0)) | 0,
        0
      );

  // const handleClose = () => {
  //   handleSubmit();
  // };

  const buttonStyle: React.CSSProperties = {
    padding: "1.25rem 2.5rem", // Equivalent to px-10 py-5
    borderRadius: "9999px", // Equivalent to rounded-full
    fontSize: "1.125rem", // Equivalent to text-lg
    fontWeight: 600, // Equivalent to font-semibold
    color: "white", // Equivalent to text-white
    background: `linear-gradient(to right, ${process.env.NEXT_PUBLIC_COLOR_BUTTON_LIGHT_1}, ${process.env.NEXT_PUBLIC_COLOR_BUTTON_LIGHT_2})`,
    transition: "transform 0.3s ease", // Equivalent to transition-colors
    ...(process.env.NEXT_PUBLIC_COLOR_BUTTONBORDER_LIGHT
      ? {
          border:
            "4px solid " + process.env.NEXT_PUBLIC_COLOR_BUTTONBORDER_LIGHT,
        }
      : {}),
    ...(process.env.NEXT_PUBLIC_COLOR_BUTTONSHADOW_LIGHT
      ? {
          boxShadow:
            "0 4px 6px " + process.env.NEXT_PUBLIC_COLOR_BUTTONSHADOW_LIGHT,
        }
      : {}),
  };

  const darkButtonStyle: React.CSSProperties = {
    background: `linear-gradient(to right, ${process.env.NEXT_PUBLIC_COLOR_BUTTON_DARK_1}, ${process.env.NEXT_PUBLIC_COLOR_BUTTON_DARK_2})`,
    ...(process.env.NEXT_PUBLIC_COLOR_BUTTONBORDER_DARK
      ? {
          border:
            "4px solid " + process.env.NEXT_PUBLIC_COLOR_BUTTONBORDER_DARK,
        }
      : {}),
    ...(process.env.NEXT_PUBLIC_COLOR_BUTTONSHADOW_DARK
      ? {
          boxShadow:
            "0 4px 6px " + process.env.NEXT_PUBLIC_COLOR_BUTTONSHADOW_DARK,
        }
      : {}),
  };

  const keyframes = `
  @keyframes glowSelected {
    0% {
      box-shadow: 0 0 15px ${process.env.NEXT_PUBLIC_COLOR_OPTIONSELECTEDSHADOW_LIGHT};
    }
    50% {
      box-shadow: 0 0 40px ${process.env.NEXT_PUBLIC_COLOR_OPTIONSELECTEDSHADOW_LIGHT};
    }
    100% {
      box-shadow: 0 0 15px ${process.env.NEXT_PUBLIC_COLOR_OPTIONSELECTEDSHADOW_LIGHT};
    }
  }
`;

  const darkKeyframes = `
    @keyframes glowSelectedDark {
    0% {
      box-shadow: 0 0 15px ${process.env.NEXT_PUBLIC_COLOR_OPTIONSELECTEDSHADOW_DARK};
    }
    50% {
      box-shadow: 0 0 40px ${process.env.NEXT_PUBLIC_COLOR_OPTIONSELECTEDSHADOW_DARK};
    }
    100% {
      box-shadow: 0 0 15px ${process.env.NEXT_PUBLIC_COLOR_OPTIONSELECTEDSHADOW_DARK};
    }
  }`;

  // Inject keyframes into the document head
  const styleSheet = document.styleSheets[0];
  styleSheet.insertRule(keyframes, styleSheet.cssRules.length);
  styleSheet.insertRule(darkKeyframes, styleSheet.cssRules.length);

  const selectedButtonStyles = {
    // "@keyframes glowSelected": {
    //   "0%": {
    //     boxShadow: `0 0 15px ${process.env.NEXT_PUBLIC_COLOR_OPTIONSELECTEDSHADOW}`,
    //   },
    //   "50%": {
    //     boxShadow: `0 0 45px ${process.env.NEXT_PUBLIC_COLOR_OPTIONSELECTEDSHADOW}`,
    //   },
    //   "100%": {
    //     boxShadow: `0 0 15px ${process.env.NEXT_PUBLIC_COLOR_OPTIONSELECTEDSHADOW}`,
    //   },
    // },
    borderGlowGreen: {
      background: process.env.NEXT_PUBLIC_COLOR_OPTIONSELECTED_LIGHT,
      border: `2px solid ${process.env.NEXT_PUBLIC_COLOR_OPTIONSELECTEDBORDER_LIGHT}`,
      borderRadius: "0.5rem",
      animation: "glowSelected 1.5s infinite linear",
      animationTimingFunction: "ease-in-out",
    } as CSSProperties,

    darkModeBorderGlowGreen: {
      background: process.env.NEXT_PUBLIC_COLOR_OPTIONSELECTED_DARK,
      border: `2px solid ${process.env.NEXT_PUBLIC_COLOR_OPTIONSELECTEDBORDER_DARK}`,
      borderRadius: "0.5rem",
      animation: "glowSelectedDark 1.5s infinite linear",
      animationTimingFunction: "ease-in-out",
    } as CSSProperties,
  };

  // Example dark mode logic
  const [isDarkMode, setIsDarkMode] = useState(false);

  useEffect(() => {
    // Check user's preference or system preference
    const mediaQuery = window.matchMedia("(prefers-color-scheme: dark)");
    const handleChange = (e: MediaQueryListEvent) => setIsDarkMode(e.matches);

    // Set initial value
    setIsDarkMode(mediaQuery.matches);

    // Add event listener
    mediaQuery.addEventListener("change", handleChange);

    // Cleanup listener on unmount
    return () => mediaQuery.removeEventListener("change", handleChange);
  }, []);

  return (
    <>
      {/* <pre>{process.env.NEXT_PUBLIC_COLOR_HEADER_1}</pre> */}
      <div className="px-[30px] py-[20px] flex items-center bg-gradient-to-r from-gray-300 to-gray-400 dark:bg-gradient-to-r dark:from-neutral-900 dark:to-neutral-800">
        {/*<Image
          src="/votehand-new.png"
          alt="x"
          width={80}
          height={80}
          //layout="fill"
          //objectFit="cover"
  ></Image>*/}
        <Label className="font-medium text-4xl pr-[3px]">{maxVotes}</Label>
        <Label className="font-normal text-md">{"票まで投票できます"}</Label>
      </div>
      {/* [ + IGNORE THE FOLLOWING: ] the value.id being number may be
      problematic as it is converted to string and yet it must be considered the
      same as its original form internally; should there be any code that
  implements it with ===, we are doomed*/}
      <form>
        {/* <p>{props.checkAns}</p> */}
        <Toaster />
        <div
          key="1"
          className="flex p-[30px] pt-[15px] space-y-3 flex-col w-full h-full"
        >
          {categories.map((category) => (
            <div key={category.ID} className="space-y-2">
              <div className="space-x-2">
                <Label className="text-2xl font-bold">{category.name}</Label>
                {/*<Label className="text-md text-[#666666] dark:text-[#999999]">
                {category.maxvotes + "票まで"}
              </Label>*/}
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
                {options
                  .filter((eachOption) => eachOption.catID == category.ID)
                  .map((option) => (
                    <label
                      key={option.ID}
                      //className="option-tile bg-white dark:bg-gray-800 rounded-lg shadow-md hover:shadow-lg transition-shadow cursor-pointer w-full border border-gray-200 dark:border-gray-700"
                      className={
                        checkboxes[option.ID as keyof typeof checkboxes]
                          ? "rounded-lg shadow-md hover:shadow-lg transition-shadow cursor-pointer w-full"
                          : /*checkboxesKeys.reduce((objAcc: any, key: string) => {
                            if (
                              options.find((eachOption) => eachOption.ID == key)
                                ?.catID == category.ID &&
                              checkboxes[key as keyof typeof checkboxes]
                            ) {
                              objAcc.push(key);
                            }
                            return objAcc;
                          }, [])*/ checkboxesKeys.reduce(
                              (objAcc: any, key: string) => {
                                if (
                                  checkboxes[key as keyof typeof checkboxes]
                                ) {
                                  objAcc.push(key);
                                }
                                return objAcc;
                              },
                              []
                            ).length == maxVotes
                          ? "bg-white dark:bg-gray-800 rounded-lg transition-shadow cursor-not-allowed w-full border-2 border-gray-300 dark:border-gray-700"
                          : "bg-white dark:bg-gray-800 rounded-lg shadow-md hover:shadow-lg transition-shadow cursor-pointer w-full border-2 border-gray-300 dark:border-gray-700"
                      }
                      style={
                        checkboxes[option.ID as keyof typeof checkboxes]
                          ? isDarkMode
                            ? selectedButtonStyles.darkModeBorderGlowGreen
                            : selectedButtonStyles.borderGlowGreen
                          : undefined
                      }
                    >
                      <div className="p-2 flex flex-col items-center justify-center space-y-1">
                        <p
                          className={
                            /*checkboxesKeys.reduce((objAcc: any, key: string) => {
                            if (
                              options.find((eachOption) => eachOption.ID == key)
                                ?.catID == category.ID &&
                              checkboxes[key as keyof typeof checkboxes]
                            ) {
                              objAcc.push(key);
                            }
                            return objAcc;
                          }, [])*/ checkboxesKeys.reduce(
                              (objAcc: any, key: string) => {
                                if (
                                  checkboxes[key as keyof typeof checkboxes]
                                ) {
                                  objAcc.push(key);
                                }
                                return objAcc;
                              },
                              []
                            ).length == maxVotes &&
                            !checkboxes[option.ID as keyof typeof checkboxes]
                              ? "text-sm text-center text-gray-200 dark:text-gray-600"
                              : "text-sm text-center text-gray-500 dark:text-gray-400"
                          }
                        >
                          {option.name}
                        </p>
                        <p
                          className={
                            /*checkboxesKeys.reduce((objAcc: any, key: string) => {
                            if (
                              options.find((eachOption) => eachOption.ID == key)
                                ?.catID == category.ID &&
                              checkboxes[key as keyof typeof checkboxes]
                            ) {
                              objAcc.push(key);
                            }
                            return objAcc;
                          }, [])*/ checkboxesKeys.reduce(
                              (objAcc: any, key: string) => {
                                if (
                                  checkboxes[key as keyof typeof checkboxes]
                                ) {
                                  objAcc.push(key);
                                }
                                return objAcc;
                              },
                              []
                            ).length == maxVotes &&
                            !checkboxes[option.ID as keyof typeof checkboxes]
                              ? "text-md md:text-sm font-semibold text-center text-gray-400 dark:text-gray-500"
                              : "text-md md:text-sm font-semibold text-center"
                          }
                        >
                          {option.description}
                        </p>
                      </div>

                      <input
                        className=" sr-only"
                        name={option.ID}
                        type="checkbox"
                        checked={
                          checkboxes[option.ID as keyof typeof checkboxes] ||
                          false
                        }
                        onChange={handleCheckboxChange}
                        disabled={
                          /*checkboxesKeys.reduce((objAcc: any, key: string) => {
                            if (
                              options.find((eachOption) => eachOption.ID == key)
                                ?.catID == category.ID &&
                              checkboxes[key as keyof typeof checkboxes]
                            ) {
                              objAcc.push(key);
                            }
                            return objAcc;
                          }, [])*/ checkboxesKeys.reduce(
                            (objAcc: any, key: string) => {
                              if (checkboxes[key as keyof typeof checkboxes]) {
                                objAcc.push(key);
                              }
                              return objAcc;
                            },
                            []
                          ).length == maxVotes &&
                          !checkboxes[option.ID as keyof typeof checkboxes]
                        }
                      />
                    </label>
                  ))}
              </div>
            </div>
          ))}
        </div>

        <div className="px-[30px] py-[20px] block items-center bg-gradient-to-r from-gray-300 to-gray-400 dark:bg-gradient-to-r dark:from-neutral-900 dark:to-neutral-800">
          <Label className="w-full font-medium text-md">
            {"投票は以上です"}
            <br />
            {"最後にご質問がございます"}
          </Label>
          <br />
          <Label className="w-full font-normal text-sm text-gray-700 dark:text-neutral-400">
            {"(該当選択肢のない質問は飛ばして結構です)"}
          </Label>
        </div>

        {/*<>
        <div className="flex p-[30px] pt-[10px] space-y-3 flex-col w-full h-full">
          <Label className="text-2xl font-bold">{"Hey"}</Label>

          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
            <Checkbox />
          </div>
        </div>
        </>*/}

        {extraQuestions.map((extraQuestion) => (
          <div key={extraQuestion.ID}>
            <div className="flex p-[30px] pt-[15px] pb-0 flex-col w-full h-full">
              <Label className="text-2xl font-bold break-keep">
                {extraQuestion.name.replaceAll("を", "を\u200B")}
              </Label>
              {
                <Label className="text-md text-gray-500 dark:text-neutral-400">
                  {extraQuestion.maxVotes
                    ? "" + extraQuestion.maxVotes + "票まで"
                    : "票数上限なし"}
                </Label>
              }

              <div className="mt-2 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
                {extraOptions
                  .filter(
                    (eachExtraOption) => eachExtraOption.QID == extraQuestion.ID
                  )
                  .map((extraOption) => (
                    <label
                      key={extraOption.ID}
                      className={
                        extraCheckboxes[
                          extraOption.ID as keyof typeof extraCheckboxes
                        ]
                          ? "rounded-lg shadow-md hover:shadow-lg transition-shadow cursor-pointer w-full flex items-center justify-center"
                          : extraCheckboxesKeys.reduce(
                              (objAcc: any, key: string) => {
                                if (
                                  extraOptions.find(
                                    (eachExtraOption) =>
                                      eachExtraOption.ID == key
                                  )?.QID == extraQuestion.ID &&
                                  extraCheckboxes[
                                    key as keyof typeof extraCheckboxes
                                  ]
                                ) {
                                  objAcc.push(key);
                                }
                                return objAcc;
                              },
                              []
                            ).length == extraQuestion.maxVotes
                          ? "bg-white dark:bg-gray-800 rounded-lg transition-shadow cursor-not-allowed w-full border-2 border-gray-300 dark:border-gray-700 flex items-center justify-center"
                          : "bg-white dark:bg-gray-800 rounded-lg shadow-md hover:shadow-lg transition-shadow cursor-pointer w-full border-2 border-gray-300 dark:border-gray-700 flex items-center justify-center"
                      }
                      style={
                        extraCheckboxes[
                          extraOption.ID as keyof typeof extraCheckboxes
                        ]
                          ? isDarkMode
                            ? selectedButtonStyles.darkModeBorderGlowGreen
                            : selectedButtonStyles.borderGlowGreen
                          : undefined
                      }
                    >
                      <div className="p-2 flex flex-col items-center justify-center space-y-2">
                        <p
                          className={
                            extraCheckboxesKeys.reduce(
                              (objAcc: any, key: string) => {
                                if (
                                  extraOptions.find(
                                    (eachExtraOption) =>
                                      eachExtraOption.ID == key
                                  )?.QID == extraQuestion.ID &&
                                  extraCheckboxes[
                                    key as keyof typeof extraCheckboxes
                                  ]
                                ) {
                                  objAcc.push(key);
                                }
                                return objAcc;
                              },
                              []
                            ).length == extraQuestion.maxVotes &&
                            !extraCheckboxes[
                              extraOption.ID as keyof typeof extraCheckboxes
                            ]
                              ? "text-md md:text-sm font-semibold text-center text-gray-400 dark:text-gray-500 break-keep"
                              : "text-md md:text-sm font-semibold text-center break-keep"
                          }
                        >
                          {extraOption.name.replaceAll("・", "・\u200B")}
                        </p>
                      </div>

                      <input
                        className=" sr-only"
                        name={extraOption.ID}
                        type="checkbox"
                        checked={
                          extraCheckboxes[
                            extraOption.ID as keyof typeof extraCheckboxes
                          ] || false
                        }
                        onChange={handleExtraCheckboxChange}
                        disabled={
                          extraCheckboxesKeys.reduce(
                            (objAcc: any, key: string) => {
                              if (
                                extraOptions.find(
                                  (eachExtraOption) => eachExtraOption.ID == key
                                )?.QID == extraQuestion.ID &&
                                extraCheckboxes[
                                  key as keyof typeof extraCheckboxes
                                ]
                              ) {
                                objAcc.push(key);
                              }
                              return objAcc;
                            },
                            []
                          ).length == extraQuestion.maxVotes &&
                          !extraCheckboxes[
                            extraOption.ID as keyof typeof extraCheckboxes
                          ]
                        }
                      />
                    </label>
                  ))}
              </div>
            </div>
          </div>
        ))}
        <section className="m-6 mb-12">
          <div className="flex justify-center">
            {/* <Button
              className="px-6 py-3 rounded-full text-lg font-semibold bg-gradient-to-r from-[#6366F1] to-[#8B5CF6] text-white dark:text-white hover:from-[#8B5CF6] hover:to-[#6366F1] transition-colors"
              variant="default"
            >
              投票を確定
            </Button> */}
            <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
              <DialogTrigger asChild>
                <Button
                  className={`px-10 py-5 rounded-full text-lg font-semibold bg-gradient-to-r text-white dark:text-white transition duration-300 ease-in-out transform hover:scale-105 ${
                    process.env.NEXT_PUBLIC_COLOR_BUTTONBORDER_LIGHT
                      ? "border-4"
                      : ""
                  } ${
                    process.env.NEXT_PUBLIC_COLOR_BUTTONBORDER_DARK
                      ? "dark:border-4"
                      : ""
                  } ${
                    process.env.NEXT_PUBLIC_COLOR_BUTTONSHADOW_LIGHT
                      ? "shadow-md"
                      : ""
                  } ${
                    process.env.NEXT_PUBLIC_COLOR_BUTTONSHADOW_DARK
                      ? "dark:shadow-md"
                      : ""
                  }`}
                  style={
                    isDarkMode
                      ? { ...buttonStyle, ...darkButtonStyle }
                      : buttonStyle
                  }
                  // type="submit"
                >
                  投票する
                </Button>
              </DialogTrigger>
              <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                  <DialogTitle>最後にご確認ください</DialogTitle>
                  {/* <DialogDescription>
                  </DialogDescription> */}
                </DialogHeader>
                {/* <ScrollArea className="h-[250px] w-full rounded-md border p-4">
                  <div className="text-sm prose dark:prose-invert">
                    <ReactMarkdown>{`
## Markdown

Lorem ipsum dolor sit amet consectetur, adipisicing elit. Magni, nemo!
`}</ReactMarkdown>
                  </div>
                </ScrollArea> */}
                <div className="space-y-4 pt-4">
                  <div className="flex items-center space-x-2">
                    <Checkbox
                      id="eligibility"
                      checked={isEligibilityChecked}
                      onCheckedChange={setIsEligibilityChecked}
                    />
                    <Label
                      htmlFor="eligibility"
                      className="text-lg font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 whitespace-pre-line"
                    >
                      本校生徒ではありません
                    </Label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Checkbox
                      id="secondEligibility"
                      checked={isSecondEligibilityChecked}
                      onCheckedChange={setIsSecondEligibilityChecked}
                    />
                    <Label
                      htmlFor="secondEligibility"
                      className="text-lg font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 whitespace-pre-line"
                    >
                      初めての投票です
                    </Label>
                  </div>
                  {/* <div className="flex items-center space-x-2">
                    <Checkbox
                      id="policy"
                      checked={isPolicyChecked}
                      onCheckedChange={setIsPolicyChecked}
                    />
                    <Label
                      htmlFor="policy"
                      className="text-md font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 whitespace-pre-line"
                    >
                      {`その他の投票条件・
                      データの取扱いに同意します`}
                    </Label>
                  </div> */}
                </div>
                <DialogFooter>
                  <Button
                    disabled={
                      !true ||
                      !isEligibilityChecked ||
                      !isSecondEligibilityChecked ||
                      isLoadingStatus
                    }
                    onClick={handleSubmit}
                    className="text-lg font-bold"
                  >
                    {isLoadingStatus ? (
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : null}
                    投票を確定
                  </Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>
        </section>
      </form>
    </>
  );
}

function CodeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  );
}
